//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace HSRM.TTC2023.ClassToRelational.Relational_
{
    
    
    /// <summary>
    /// The public interface for Column
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Column))]
    [XmlDefaultImplementationTypeAttribute(typeof(Column))]
    [ModelRepresentationClassAttribute("https://github.com/ATL-Research/incremental-class2relational/Relational.nmeta#//C" +
        "olumn")]
    public interface IColumn : IModelElement, INamed
    {
        
        /// <summary>
        /// The owner property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("owner")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("col")]
        ITable Owner
        {
            get;
            set;
        }
        
        /// <summary>
        /// The keyOf property
        /// </summary>
        [DisplayNameAttribute("keyOf")]
        [CategoryAttribute("Column")]
        [XmlElementNameAttribute("keyOf")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("key")]
        ITable KeyOf
        {
            get;
            set;
        }
        
        /// <summary>
        /// The type property
        /// </summary>
        [DisplayNameAttribute("type")]
        [CategoryAttribute("Column")]
        [XmlElementNameAttribute("type")]
        [XmlAttributeAttribute(true)]
        HSRM.TTC2023.ClassToRelational.Relational_.IType Type
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Owner property changes its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> OwnerChanging;
        
        /// <summary>
        /// Gets fired when the Owner property changed its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> OwnerChanged;
        
        /// <summary>
        /// Gets fired before the KeyOf property changes its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> KeyOfChanging;
        
        /// <summary>
        /// Gets fired when the KeyOf property changed its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> KeyOfChanged;
        
        /// <summary>
        /// Gets fired before the Type property changes its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> TypeChanging;
        
        /// <summary>
        /// Gets fired when the Type property changed its value
        /// </summary>
        event System.EventHandler <ValueChangedEventArgs> TypeChanged;
    }
}

