//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace HSRM.TTC2023.ClassToRelational.Relational_
{
    
    
    /// <summary>
    /// The public interface for Table
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Table))]
    [XmlDefaultImplementationTypeAttribute(typeof(Table))]
    [ModelRepresentationClassAttribute("https://github.com/ATL-Research/incremental-class2relational/Relational.nmeta#//T" +
        "able")]
    public interface ITable : IModelElement, INamed
    {
        
        /// <summary>
        /// The col property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("col")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("owner")]
        [ConstantAttribute()]
        IOrderedSetExpression<IColumn> Col
        {
            get;
        }
        
        /// <summary>
        /// The key property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [DisplayNameAttribute("key")]
        [CategoryAttribute("Table")]
        [XmlElementNameAttribute("key")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("keyOf")]
        [ConstantAttribute()]
        ISetExpression<IColumn> Key
        {
            get;
        }
    }
}

