//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.15
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace HSRM.TTC2023.ClassToRelational.Class_
{
    
    
    public class ClassAttrCollection : ObservableOppositeOrderedSet<HSRM.TTC2023.ClassToRelational.Class_.IClass, HSRM.TTC2023.ClassToRelational.Class_.IAttribute>
    {
        
        public ClassAttrCollection(HSRM.TTC2023.ClassToRelational.Class_.IClass parent) : 
                base(parent)
        {
        }
        
        private void OnItemParentChanged(object sender, ValueChangedEventArgs e)
        {
            if ((e.NewValue != this.Parent))
            {
                this.Remove(((HSRM.TTC2023.ClassToRelational.Class_.IAttribute)(sender)));
            }
        }
        
        protected override void SetOpposite(HSRM.TTC2023.ClassToRelational.Class_.IAttribute item, HSRM.TTC2023.ClassToRelational.Class_.IClass parent)
        {
            if ((parent != null))
            {
                item.ParentChanged += this.OnItemParentChanged;
                item.Owner = parent;
            }
            else
            {
                item.ParentChanged -= this.OnItemParentChanged;
                if ((item.Owner == this.Parent))
                {
                    item.Owner = parent;
                }
            }
        }
    }
}

