/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JClass2RelationalIncremental;

import atl.research.AbstractDriver;
import transformations.incremental.Class2RelationalIncremental;

public class App extends AbstractDriver {
	
	// static run
	public static void main(String[] args) {
		App solution = new App();
		
		try {
			solution.init();
			
			if (solution.isBatchMode()) {
				solution.applyChange();
				solution.applyTransformation();
			}
			else {
				solution.applyTransformation();
				solution.applyChange();
			}
			solution.saveTarget();
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}

	// run via AbstractDriver
	@Override
	protected void applyTransformation() {		
		Class2RelationalIncremental.start(this.getSource(), this.getTarget());
	}

}
