enableGlobalCache: false

enableTelemetry: false

logFilters:
  - level: discard
    text: "prettier is listed by your project with version 3.1.0, which doesn't satisfy what @xstate/cli (p708d6) and other dependencies request (^2.0.0)."

nodeLinker: pnp

packageExtensions:
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
