//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.16
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Changes;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace HSRM.TTC2023.ClassToRelational.Changes
{
    
    
    /// <summary>
    /// The public interface for DeleteFromRoot
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(DeleteFromRoot))]
    [XmlDefaultImplementationTypeAttribute(typeof(DeleteFromRoot))]
    [ModelRepresentationClassAttribute("https://github.com/ATL-Research/incremental-class2relational/Changes.nmeta#//DeleteFromRoot")]
    public interface IDeleteFromRoot : NMF.Models.IModelElement, NMF.Models.Changes.IElementaryChange
    {
        
        /// <summary>
        /// The deletedElement property
        /// </summary>
        [DisplayNameAttribute("deletedElement")]
        [CategoryAttribute("DeleteFromRoot")]
        [XmlElementNameAttribute("deletedElement")]
        [XmlAttributeAttribute(true)]
        NMF.Models.IModelElement DeletedElement
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the DeletedElement property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeletedElementChanging;
        
        /// <summary>
        /// Gets fired when the DeletedElement property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> DeletedElementChanged;
    }
}

