name: Label

on:
  push:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          
      - name: Install docker
        uses: papodaca/install-docker-action@main
        
      - run: |
          cd metrics
          make

      - name: Archive plots artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plots
          path: |
            metrics/plots/*.pdf
